# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: 'latest'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'FHIRCONTAINER'
        repository: 'MSFHIRSTU3'
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile.Stu3'
        tags: |
          $(tag)
